# Use the official Nginx image as the base
FROM nginx:latest

# Copy the custom Nginx configuration file
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Remove default Nginx static content
RUN rm -rf /usr/share/nginx/html/*

# Copy the static frontend files into the Nginx web root
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx after a short delay to allow backend to initialize
CMD ["/bin/sh", "-c", "sleep 10 && nginx -g 'daemon off;'"]
